#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Cookie 管理模块
支持手动和自动获取 Bilibili Cookie
"""

import os
import re
import time
from typing import Optional, Dict, List


class CookieManager:
    """Cookie 管理器"""
    
    def __init__(self, cookie_path: str = None):
        """
        :param cookie_path: Cookie 文件路径，默认为 bilibili_downloader/bilibili_cookies.txt
        """
        if cookie_path:
            self.cookie_path = cookie_path
        else:
            # 默认路径：当前目录下的 bilibili_cookies.txt
            self.cookie_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "bilibili_cookies.txt")
    
    def guide_user_to_get_cookie(self):
        """指导用户获取 Cookie"""
        print("""
╔═══════════════════════════════════════════════════════════╗
║              Bilibili Cookie 获取指南                       ║
╠═══════════════════════════════════════════════════════════╣
║  步骤 1: 打开浏览器 (Chrome/Edge/Firefox)                   ║
║  步骤 2: 访问 https://www.bilibili.com 并登录账号           ║
║  步骤 3: 按 F12 打开开发者工具                               ║
║  步骤 4: 切换到 Network (网络) 标签                          ║
║  步骤 5: 刷新页面 (F5)                                      ║
║  步骤 6: 找到任意一个 Bilibili 的 API 请求                      ║
║  步骤 7: 在请求头 (Headers) 中找到 Cookie                     ║
║  步骤 8: 复制 Cookie 值并保存到文件                           ║
╚═══════════════════════════════════════════════════════════╝
        """)
    
    def get_cookies_from_playwright(self) -> bool:
        """使用 Playwright 自动获取 Cookie"""
        try:
            from playwright.sync_api import sync_playwright
            
            print("\n正在启动浏览器...")
            
            with sync_playwright() as p:
                # 启动浏览器
                browser = p.chromium.launch(headless=False)
                context = browser.new_context(
                    user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
                )
                page = context.new_page()
                
                print("请手动登录 Bilibili 账号...")
                print("登录完成后，请关闭浏览器窗口")
                
                # 访问 Bilibili
                page.goto("https://www.bilibili.com", wait_until='networkidle')
                
                # 等待用户登录
                while True:
                    # 检查是否已登录
                    cookie_names = [c['name'] for c in context.cookies()]
                    if 'SESSDATA' in cookie_names:
                        print("✓ 检测到登录状态")
                        break
                    
                    time.sleep(1)
                
                # 等待用户确认
                print("\n登录成功！正在获取 Cookie...")
                time.sleep(3)  # 等待用户关闭浏览器
                
                # 获取 Cookie
                cookies = context.cookies()
                
                # 保存到文件
                self._save_cookies(cookies)
                
                browser.close()
                
                print(f"✓ Cookie 已保存到：{self.cookie_path}")
                return True
                
        except Exception as e:
            print(f"✗ 获取 Cookie 失败：{e}")
            return False
    
    def _save_cookies(self, cookies: List[Dict]):
        """保存 Cookie 到文件"""
        os.makedirs(os.path.dirname(self.cookie_path) if os.path.dirname(self.cookie_path) else '.', exist_ok=True)
        
        with open(self.cookie_path, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
            f.write("# This file was generated by a tool. Edit at your own risk.\n\n")
            
            for cookie in cookies:
                # 格式：domain flag path secure expiration name value
                domain = cookie.get('domain', '')
                flag = 'TRUE' if domain.startswith('.') else 'FALSE'
                path = cookie.get('path', '/')
                secure = 'TRUE' if cookie.get('secure') else 'FALSE'
                expiration = int(cookie.get('expires', 0)) if cookie.get('expires') else 0
                name = cookie.get('name', '')
                value = cookie.get('value', '')
                
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")
    
    def is_logged_in(self) -> bool:
        """检查是否有有效 Cookie"""
        if not os.path.exists(self.cookie_path):
            print(f"Cookie 文件不存在：{self.cookie_path}")
            return False
        
        try:
            with open(self.cookie_path, 'r', encoding='utf-8') as f:
                content = f.read()
                # 检查是否包含关键 Cookie
                has_sessdata = 'SESSDATA' in content
                if has_sessdata:
                    print(f"✓ Cookie 已设置：{self.cookie_path}")
                return has_sessdata
        except Exception as e:
            print(f"读取 Cookie 失败：{e}")
            return False
    
    def get_cookie_dict(self) -> Dict[str, str]:
        """获取 Cookie 字典"""
        cookies = {}
        if os.path.exists(self.cookie_path):
            try:
                with open(self.cookie_path, 'r', encoding='utf-8') as f:
                    for line in f:
                        line = line.strip()
                        if line and not line.startswith('#'):
                            parts = line.split('\t')
                            if len(parts) >= 7:
                                cookies[parts[5]] = parts[6]
            except Exception as e:
                print(f"读取 Cookie 失败：{e}")
        return cookies
    
    def clear_cookie(self):
        """清除 Cookie"""
        if os.path.exists(self.cookie_path):
            os.remove(self.cookie_path)
            print("Cookie 文件已删除")
        else:
            print("没有找到 Cookie 文件")
    
    def set_cookie(self, cookie_str: str):
        """从字符串设置 Cookie"""
        # 将 Cookie 字符串转换为文件格式
        cookies = []
        for part in cookie_str.split(';'):
            part = part.strip()
            if '=' in part:
                name, value = part.split('=', 1)
                # 创建虚拟 cookie 对象
                cookies.append({
                    'domain': '.bilibili.com',
                    'path': '/',
                    'secure': True,
                    'expires': 0,
                    'name': name.strip(),
                    'value': value.strip()
                })
        
        if cookies:
            self._save_cookies(cookies)
            print("Cookie 已设置")
        else:
            print("Cookie 格式无效")
